/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const UtilCriteriasValues = t.iface([], {
    "criterias": "CardComponentFields",
});

const UtilCriteriasComponent_ts: t.ITypeSuite = {
    UtilCriteriasValues,
};
export default UtilCriteriasComponent_ts;
