/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PCResultValues = t.iface(["EvaluationValues"], {
});

const PCResultComponent_ts: t.ITypeSuite = {
  PCResultValues,
};
export default PCResultComponent_ts;
