/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PortWeightingValues = t.iface([], {
  "attractivity": "CompareComponentValues",
  "comp-standing": "CompareComponentValues",
});

const PortWeightingComponent_ts: t.ITypeSuite = {
  PortWeightingValues,
};
export default PortWeightingComponent_ts;
