/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PortCreateObjectsValues = t.iface([], {
  "objects": "CardComponentFields",
});

const PortObjectsComponent_ts: t.ITypeSuite = {
  PortCreateObjectsValues
};
export default PortObjectsComponent_ts;
