/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TestCoordinateSystemValues = t.iface([], {
    "points": t.array("Point"),
});

const TestCoordinateSystemComponent_ts: t.ITypeSuite = {
    TestCoordinateSystemValues
};
export default TestCoordinateSystemComponent_ts;
