/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PCCriteriasValues = t.iface([], {
  "criterias": "CardComponentFields",
});

export const PCCriteriasState = t.iface([], {
});

const PCCriteriasComponent_ts: t.ITypeSuite = {
  PCCriteriasValues,
  PCCriteriasState,
};
export default PCCriteriasComponent_ts;
