/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const UtilWeightingValues = t.iface(["CompareComponentValues"], {});

const UtilWeightingComponent_ts: t.ITypeSuite = {
    UtilWeightingValues,
};
export default UtilWeightingComponent_ts;
