/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Point = t.iface([], {
    "x": "number",
    "y": "number",
    "sizeMultiplier": "number",
    "header": "string",
    "color": "string",
});

const Point_ts: t.ITypeSuite = {
    Point,
};
export default Point_ts;
