/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TestComparecomponentValues = t.iface([], {});

const TestComparecomponent_ts: t.ITypeSuite = {
    TestComparecomponentValues
};
export default TestComparecomponent_ts;
