/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PortfolioAnalysisValues = t.iface([], {
    "port-objects": "PortCreateObjectsValues",
    "port-criterias": t.opt("PortCriteriasValues"),
    "port-weighting": t.opt("PortWeightingValues"),
    "port-evaluation": t.opt("PortEvaluationValues"),
    "port-result": t.opt("PortResultValues"),
});

const PortfolioAnalysis_ts: t.ITypeSuite = {
    PortfolioAnalysisValues,
};
export default PortfolioAnalysis_ts;
