/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PersonaSummaryValues = t.union("null", "undefined");

const PersonaSummary_ts: t.ITypeSuite = {
    PersonaSummaryValues,
};
export default PersonaSummary_ts;
