/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PortCriteriasValues = t.iface([], {
    "attractivity": "CardComponentFields",
    "comp-standing": "CardComponentFields",
});

const PortCriteriasComponent_ts: t.ITypeSuite = {
    PortCriteriasValues,
};
export default PortCriteriasComponent_ts;
