/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PortResultValues = t.iface([], {
  "results": t.iface([], {
    "attractivity": "ResultEvaluationValue",
    "comp-standing": "ResultEvaluationValue",
  }),
  "points": t.array("Point"),
});

const PortResultComponent_ts: t.ITypeSuite = {
  PortResultValues,
};
export default PortResultComponent_ts;
