/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AlternateAction = t.iface([], {
    "name": "string",
    "hasNone": "boolean",
    "alternatives": "CardComponentFields",
});

export const SWOTAlternativeActionsValues = t.iface([], {
    "actions": t.array("AlternateAction"),
});


const SWOTAlternativeActionsComponent_ts: t.ITypeSuite = {
    AlternateAction,
    SWOTAlternativeActionsValues,
};
export default SWOTAlternativeActionsComponent_ts;
