/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes
export const PersonaFactorsValues = t.iface([], {
    "factors": t.iface([], {
        "qualifikation": "CardComponentFields",
        "art_der_Erkrankung": "CardComponentFields",
        "beraterOrAngehörige": "CardComponentFields",
        "familieOrFreunde": "CardComponentFields",
        "charaktereigenschaften": "CardComponentFields",
        "bedürfnisse": "CardComponentFields",
        "hobies": "CardComponentFields",
        "motivation": "CardComponentFields",
        "zitat": "CardComponentFields",
    }),
});

const PersonaFactorsComponent_ts: t.ITypeSuite = {
    PersonaFactorsValues,
};
export default PersonaFactorsComponent_ts;
