/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PairwiseComparisonValues_ti = t.iface([], {
    "pc-criterias": "PCCriteriasValues",
    "pc-comparison": t.opt("PCPairComparisonValues"),
    "pc-result": t.opt("PCResultValues"),
});

const PairwiseComparison_ts: t.ITypeSuite = {
    PairwiseComparisonValues_ti,
};
export default PairwiseComparison_ts;
