/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TestResourcesValues = t.iface([], {});

const TestResourcesComponent_ts: t.ITypeSuite = {
    TestResourcesValues
};
export default TestResourcesComponent_ts;
