/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const SingleResult = t.iface([], {
    "criteria": "CardComponentField",
    "points": "number",
    "rank": "number",
});

export const EvaluationValues = t.iface([], {
    "result": t.array("SingleResult"),
    "resultAsString": "string",
});

const WeightingEvaluation_ts: t.ITypeSuite = {
    SingleResult,
    EvaluationValues,
};
export default WeightingEvaluation_ts;
