/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const CardComponentFieldsWithName = t.array("CardComponentFieldsWithNameValues");

export const CardComponentFieldsWithNameValues = t.iface([], {
    "name": "string",
    "fields": "CardComponentFields"
});

const CardComponentWithName_ts: t.ITypeSuite = {
    CardComponentFieldsWithName,
    CardComponentFieldsWithNameValues
};
export default CardComponentWithName_ts;
