/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const CompareHeader = t.iface([], {
  "header": "string",
  "desc": t.opt("string"),
});

const CompareHeaderAdapter_ts: t.ITypeSuite = {
  CompareHeader,
};
export default CompareHeaderAdapter_ts;
