/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const UtilInvestigationObjectsValues = t.iface([], {
    "objects": "CardComponentFields",
});

const UtilInvestigationObjectsComponent_ts: t.ITypeSuite = {
    UtilInvestigationObjectsValues,
};
export default UtilInvestigationObjectsComponent_ts;
