/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TestCardcomponentValues = t.iface([], {
    "cards": "CardComponentFields",
});

const TestCardcomponentComponent_ts: t.ITypeSuite = {
    TestCardcomponentValues
};
export default TestCardcomponentComponent_ts;
