/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PersonaAnalysisValues = t.iface([], {
    "persona-factors": "PersonaFactorsValues",
    "uploadImage_actions":t.opt("UpdateImgValues"),
    "persona-factors2": "PersonaFactorsValues2"
});

const PersonaAnalysis_ts: t.ITypeSuite = {
    PersonaAnalysisValues,
};
export default PersonaAnalysis_ts;
