/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PersonaPersonalityValues = t.iface([], {
    "fields": t.iface([], {
        "demograph": "CardComponentFields",
        "pains": "CardComponentFields",
        "gains": "CardComponentFields"
    }),
    "individual": "CardComponentFieldsWithName",
    "fieldsElse": t.iface([], {
        "statements": "CardComponentFields",
        "motives": "CardComponentFields",
        "keywords": "CardComponentFields"
    })
});

const PersonaPersonality_ts: t.ITypeSuite = {
    PersonaPersonalityValues,
}

export default PersonaPersonality_ts;
