/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PCPairComparisonValues = t.iface(["CompareComponentValues"], {});

const PCPairComparisonComponent_ts: t.ITypeSuite = {
    PCPairComparisonValues,
};
export default PCPairComparisonComponent_ts;
