/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TestSubstepsValues = t.iface([], {
    "ratings": t.array("number"),
});

const TestSubstepsComponent_ts: t.ITypeSuite = {
    TestSubstepsValues
};
export default TestSubstepsComponent_ts;
