/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TestAnalysisValues = t.iface([], {
    "test-cardcomponent": "TestCardcomponentValues",
    "test-comparecomponent": t.opt("TestComparecomponentValues"),
    "test-resources": t.opt("TestResourcesValues"),
    "test-substeps": t.opt("TestSubstepsValues"),
    "test-coordinate-system": t.opt("TestCoordinateSystemValues"),
});

const TestAnalysis_ts: t.ITypeSuite = {
    TestAnalysisValues
};
export default TestAnalysis_ts;
